{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-store-csi-driver
  namespace: {{ default .Release.Namespace .Values.namespace }}
{{ include "sscd.labels" . | indent 2 }}
{{ end }}
